// Code generated by goctl. DO NOT EDIT.
package types

type BasicReply struct {
	Code int64  `json:"status_code"`
	Msg  string `json:"status_msg"`
}

type LoginReq struct {
	Username string `form:"username"`
	Password string `form:"password"`
}

type LoginResp struct {
	BasicReply
	UserId int    `json:"user_id"`
	Token  string `json:"token"`
}

type RegisterReq struct {
	Username string `form:"username"`
	Password string `form:"password"`
}

type RegisterResp struct {
	BasicReply
	UserId int64  `json:"user_id"`
	Token  string `json:"token"`
}

type User struct {
	Id            int64  `json:"id"`
	Name          string `json:"name"`
	FollowCount   int64  `json:"follow_count"`
	FollowerCount int64  `json:"follower_count"`
	IsFollowed    bool   `json:"is_followed"`
}
