// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	user "tiktok-app-microservice/service/http/internal/handler/user"
	"tiktok-app-microservice/service/http/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: user.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: user.RegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/tiktok/user"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/fansList",
				Handler: user.FansListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/follow",
				Handler: user.FollowHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/followList",
				Handler: user.FollowListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/getUserInfo",
				Handler: user.GetUserInfoHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/tiktok/user"),
	)
}
